[source]
type = "N2N"
address = ["Tcp", "relay1.example:3001"]
magic = 42

[source.mapper]
include_block_cbor = false

[chain]
type = "custom"
magic = 42
address_hrp = "addr_test"
adahandle_policy = ""
byron_epoch_length = 86400
byron_slot_length = 1
byron_known_slot = 0
byron_known_hash = ""
byron_known_time = 0
shelley_epoch_length = 86400
shelley_slot_length = 1
shelley_known_slot = 0
shelley_known_hash = ""
shelley_known_time = 0

[sink]
type = "Stdout"
