# shellcheck shell=bash

format:
   #!/usr/bin/env bash
   fourmolu -i src app test
   cabal-fmt -i tracer-sidecar.cabal
   nixfmt *.nix
   nixfmt nix/*.nix

hlint:
  #!/usr/bin/env bash
  hlint app src test

build:
    #!/usr/bin/env bash
    cabal build all --enable-tests --enable-benchmarks

test args='':
  #!/usr/bin/env bash
  # shellcheck disable=SC2157
  if [ -n "{{ args }}" ]; then
    cabal test --test-show-details=streaming --test-options="--match" \
    --test-options="{{args}}"
  else
    cabal test --test-show-details=streaming
  fi

CI:
  #!/usr/bin/env bash
  just format
  just hlint
  just build
  just test

load-docker-image:
    #!/usr/bin/env bash
    set -euo pipefail
    nix build .#docker-image
    docker load < result
    version=$(nix eval --raw .#version)
    echo "image tag: "$version