load-docker-image:
    #!/usr/bin/env bash
    set -euo pipefail
    nix build .#docker-image
    docker load < result
    version=$(nix eval --raw .#version)
    echo "image tag: "$version

format:
    #!/usr/bin/env bash
    set -euo pipefail
    nixfmt *.nix
    nixfmt nix/*.nix