# shellcheck shell=bash

format:
    #!/usr/bin/env bash
    set -euo pipefail
    fourmolu -i src app
    cabal-fmt -i asteria-game.cabal
    nixfmt *.nix
    nixfmt nix/*.nix

hlint:
    #!/usr/bin/env bash
    hlint src app

build:
    #!/usr/bin/env bash
    cabal build all

load-docker-image:
    #!/usr/bin/env bash
    set -euo pipefail
    nix build .#docker-image
    version=$(nix eval --raw .#version)
    docker load < ./result
    docker tag \
      "ghcr.io/cardano-foundation/cardano-node-antithesis/asteria-game:$version" \
      ghcr.io/cardano-foundation/cardano-node-antithesis/asteria-game:dev
    echo "image tag: $version (also tagged :dev)"

CI:
    #!/usr/bin/env bash
    set -euo pipefail
    just format
    just hlint
    just build
